# -*- coding: utf-8 -*-
"""Exercise 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XIHfwH9iCWBPNXsaT0xNZ0DSWqegiJhT
"""

!pip install wordcloud

from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt

with open('/content/JaneEyre.txt', 'r') as file:
    text = file.read()

from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt

wordcloud = WordCloud(
    width=800,
    height=400,
    background_color="white",
    stopwords=set(STOPWORDS),
    min_font_size=10,
    ).generate(text)

plt.figure(figsize=(8, 8), facecolor=None)
plt.imshow(wordcloud)
plt.axis("off")
plt.tight_layout(pad=0)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
from wordcloud import WordCloud, STOPWORDS

mask_path = '/content/clip-art-jesus-silhouette-jesus-shadow.jpg'
mask_image = np.array(Image.open(mask_path))

text = "Jesus is a central figure in Christianity, revered by many as the Son of God."


wordcloud_masked = WordCloud(
    background_color='white',
    mask=mask_image,
    contour_color='black',
    contour_width=1,
    colormap='viridis',
    max_words=100,
    stopwords=STOPWORDS,
    width=800,
    height=400
).generate(text)
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud_masked, interpolation='bilinear')
plt.axis("off")
plt.show()

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
from wordcloud import WordCloud, STOPWORDS

mask_path = '/content/batman.jpg'
mask_image = np.array(Image.open(mask_path))

text = "Batman is a fictional superhero appearing in American comic books published by DC Comics. " \
       "He is a vigilante who fights crime using intellect, physical prowess, and advanced technology."

wordcloud_masked = WordCloud(
    background_color='white',
    mask=mask_image,
    contour_color='black',
    contour_width=1,
    colormap='plasma',
    max_words=100,
    stopwords=STOPWORDS,
    width=800,
    height=400
).generate(text)

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud_masked, interpolation='bilinear')
plt.axis("off")
plt.show()

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
from wordcloud import WordCloud, STOPWORDS

mask_path = '/content/batman.jpg'
mask_image = np.array(Image.open(mask_path))

text = "Batman is a fictional superhero appearing in American comic books published by DC Comics. " \
       "He is a vigilante who fights crime using intellect, physical prowess, and advanced technology."

wordcloud_masked = WordCloud(
    background_color='black',
    mask=mask_image,
    contour_color='yellow',
    contour_width=1,
    colormap='plasma',
    max_words=100,
    stopwords=STOPWORDS,
    width=800,
    height=400
).generate(text)

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud_masked, interpolation='bilinear')
plt.axis("off")
plt.show()

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
from wordcloud import WordCloud, STOPWORDS

mask_path = '/content/spide.jpeg'
mask_image = np.array(Image.open(mask_path))

text = "Spider-Man is a fictional superhero created by writer Stan Lee and writer-artist Steve Ditko. " \
       "First appearing in Amazing Fantasy #15 in 1962, Spider-Man is the alter ego of Peter Parker, " \
       "a young man who gains superpowers after being bitten by a radioactive spider. He possesses enhanced strength, " \
       "agility, and the ability to cling to walls, as well as a sixth sense known as 'spider-sense' that alerts him " \
       "to danger. Spider-Man is known for his web-slinging abilities, allowing him to travel through the city " \
       "and fight crime. His motto, 'With great power comes great responsibility,' reflects his commitment to protecting " \
       "the innocent and combating villains like the Green Goblin, Doctor Octopus, and Venom."

wordcloud_masked = WordCloud(
    background_color='black',
    mask=mask_image,
    contour_color='red',
    contour_width=1,
    colormap='cool',
    max_words=100,
    stopwords=STOPWORDS,
    width=800,
    height=400
).generate(text)

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud_masked, interpolation='bilinear')
plt.axis("off")
plt.show()