# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ftURsGJ1ibpWb9VspTIds69xdlJ-sfvI
"""

!pip install nltk



import nltk
nltk.download('punkt')

from nltk.tokenize import word_tokenize

text = "Technology has revolutionized education in many ways. Online resources, interactive tools, and virtual classrooms have made learning more accessible. However, there are concerns about screen time and digital distractions. Finding the right balance is key to ensuring technology enhances learning."

tokens = word_tokenize(text)

print("Tokens:", tokens)

print("Number of tokens:", len(tokens))

from nltk.probability import FreqDist

freq_dist = FreqDist(tokens)
print("Token frequencies:", freq_dist.most_common(10))  # Show the 10 most common tokens

